=== JMMC-OpenDev/mfgui/config/mfmdl.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--
Document   : mfmdl.xsd
Created on : 19 juillet 2006, 10:25
Author     : mella
Description:

The form is quite simple:
models are generic and can be nested using a simple model with type attribute
valued to the composite value

-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
argetNamespace="http://jmmc.fr/mf/model" elementFormDefault="qualified">

<xsd:annotation>
<xsd:documentation>
This is a XML Schema for jmmc model fitting models.
</xsd:documentation>
</xsd:annotation>

<!--
Basic model representation. This model also correspond to composite model 
-->
<xsd:element name="model">
<xsd:annotation>
<xsd:documentation>
A common representation of every models.
</xsd:documentation>
</xsd:annotation>

<xsd:complexType >
<xsd:sequence>
<xsd:element ref="model" minOccurs="0" maxOccurs="unbounded"/>
<xsd:element ref="parameter" minOccurs="1" maxOccurs="unbounded" />
</xsd:sequence>
<xsd:attributeGroup ref="ModelAttributes"/>
</xsd:complexType>

</xsd:element>
<!--
Model parameter representation.
-->
<xsd:element name="parameter">
<xsd:annotation>
<xsd:documentation>
A common representation of every model parameters.
</xsd:documentation>
</xsd:annotation>

<xsd:complexType>
<xsd:sequence>
<xsd:element name="desc" type="xsd:string" minOccurs="0" maxOccurs="1"/>
<xsd:element name="units" type="xsd:string" minOccurs="0" maxOccurs="1"/>
<xsd:element name="value" type="xsd:long" minOccurs="1" maxOccurs="1"/>
<xsd:element name="fixed" type="xsd:boolean" minOccurs="1" maxOccurs="1"/>
<xsd:element name="minValue" type="xsd:long" minOccurs="0" maxOccurs="1"/>
<xsd:element name="maxValue" type="xsd:long" minOccurs="0" maxOccurs="1"/>
<xsd:element name="editable" type="xsd:boolean" minOccurs="1" maxOccurs="1"/>
</xsd:sequence>
<xsd:attributeGroup ref="ParameterAttributes"/>
</xsd:complexType>
</xsd:element>

<!-- Model attributes -->
<xsd:attributeGroup name="ModelAttributes">
<xsd:attribute name="name" type="xsd:string" use="required"/>
<xsd:attribute name="type" type="xsd:string" use="required"/>
</xsd:attributeGroup>

<!-- Parameters attributes -->
<xsd:attributeGroup name="ParameterAttributes">
<xsd:attribute name="name" type="xsd:string" use="required"/>
</xsd:attributeGroup>

</xsd:schema>

=== JMMC-OpenDev/mfgui/mfgui/test/m.xml
<?xml version='1.0' encoding='UTF-8'?>
<model name='cm1' type='composed_model'
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='mfmdl.xsd'>
    <model name='m1' type='ponct'>
        <parameter name='p11'><value>1</value><fixed>false</fixed></parameter>
        <parameter name='p12'><value>1</value><fixed>false</fixed></parameter>
        <parameter name='p13'><value>1</value><fixed>false</fixed></parameter>
        <parameter name='p14'><value>1</value><fixed>false</fixed></parameter>
    </model>
    <model name='m2' type='ponct'>
        <parameter name='p21'><value>1</value><fixed>false</fixed></parameter>
        <parameter name='p22'><value>1</value><fixed>false</fixed></parameter>
        <parameter name='p23'><value>1</value><fixed>false</fixed></parameter>
        <parameter name='p24'><value>1</value><fixed>false</fixed></parameter>
    </model>
    <model name='cm2' type='composed_model' >
        <model name='m21' type='ponct'>
            <parameter name='p211'><value>1</value><fixed>false</fixed></parameter>
            <parameter name='p212'><value>1</value><fixed>false</fixed></parameter>
            <parameter name='p213'><value>1</value><fixed>false</fixed></parameter>
            <parameter name='p214'><value>1</value><fixed>false</fixed></parameter>
        </model>
        <model name='m22' type='ponct'>
            <parameter name='p221'><value>1</value><fixed>false</fixed></parameter>
            <parameter name='p222'><value>1</value><fixed>false</fixed></parameter>
            <parameter name='p223'><value>1</value><fixed>false</fixed></parameter>
            <parameter name='p224'><value>1</value><fixed>false</fixed></parameter>
        </model>
        <parameter name='p201'><value>1</value><fixed>false</fixed></parameter>
    </model>
    <model name='m21' type='ponct'>
        <parameter name='p211'><value>1</value><fixed>false</fixed></parameter>
        <parameter name='p212'><value>1</value><fixed>false</fixed></parameter>
        <parameter name='p213'><value>1</value><fixed>false</fixed></parameter>
        <parameter name='p214'><value>1</value><fixed>false</fixed></parameter>
    </model>
    <parameter name='p01'><value>1</value><fixed>false</fixed></parameter>
</model>
